### ISSUE TITLE
Trim le bloc de description sur le profil

### ISSUE THREAD

**Issue by lapin-b** [outout14/tuxbot-bot#8]
Sur le bloc de description d'un type qui a une CI, il peut y avoir un saut de ligne inutile car l'utilisateur a décidé de faire une description sur plusieurs lignes comme le montre le screen en bas.

![Le bloc avec la fameuse ligne vide](https://i.imgur.com/jRCliAv.png)

**Comment by outout14** [comment]
Je corrige ça dès que possible :wink: (désolé pour le temps d'attente)
